Added create-react-class
RickWong/react-inline-css pull request #20
Opened 2017-06-09 11:28 UTC by Floriferous

Fixes #19.

2017-06-11 02:38 UTC, willbutler requested changes
You'll want to add create-react-class to the dependencies in package.json.

2017-06-12 10:40 UTC, Floriferous commented
Obviously :) thanks!

2017-06-25 21:15 UTC, willbutler approved these changes

2017-06-25 21:15 UTC, merged

2018-02-15 14:10 UTC, Floriferous commented
Not sure why, but this came back to bite me this morning. I see in the history that I was confusing `react-create-class` and `create-react-class`, which I didn't correct inside package.json.